# Generated by Django 6.0.7 on 2026-07-22 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('SettingID', models.AutoField(primary_key=True, serialize=False)),
                ('ClinicName', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=100)),
                ('GSTNumber', models.CharField(max_length=30)),
                ('WorkingHours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('DoctorID', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Experience', models.IntegerField()),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=100)),
                ('AvailableDays', models.CharField(max_length=100)),
                ('Status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('InvoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceDate', models.DateField(auto_now_add=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('GST', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('NetAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(default='Unpaid', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField()),
                ('BloodGroup', models.CharField(blank=True, max_length=5, null=True)),
                ('Allergies', models.TextField(blank=True, null=True)),
                ('MedicalHistory', models.TextField(blank=True, null=True)),
                ('RegistrationDate', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=100)),
                ('JoiningDate', models.DateField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=20)),
                ('LastLogin', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentDate', models.DateField()),
                ('AppointmentTime', models.TimeField()),
                ('Purpose', models.CharField(max_length=200)),
                ('Status', models.CharField(default='Scheduled', max_length=20)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctors')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentDate', models.DateField(auto_now_add=True)),
                ('AmountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentMode', models.CharField(max_length=20)),
                ('TransactionID', models.CharField(blank=True, max_length=100, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoices')),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('VisitID', models.AutoField(primary_key=True, serialize=False)),
                ('VisitDate', models.DateField()),
                ('Symptoms', models.TextField()),
                ('Diagnosis', models.TextField()),
                ('DoctorNotes', models.TextField()),
                ('NextVisitDate', models.DateField(blank=True, null=True)),
                ('AppointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appointments')),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('TreatmentID', models.AutoField(primary_key=True, serialize=False)),
                ('TreatmentName', models.CharField(max_length=100)),
                ('ToothNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Procedure', models.TextField()),
                ('TreatmentCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(default='Completed', max_length=20)),
                ('VisitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.visits')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('PrescriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=100)),
                ('Dosage', models.CharField(max_length=100)),
                ('Frequency', models.CharField(max_length=50)),
                ('Days', models.IntegerField()),
                ('Instructions', models.TextField(blank=True, null=True)),
                ('VisitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.visits')),
            ],
        ),
        migrations.AddField(
            model_name='invoices',
            name='VisitID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.visits'),
        ),
    ]
