# Generated by Django 6.0.7 on 2026-07-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='AfterImage',
            field=models.ImageField(blank=True, null=True, upload_to='treatments/'),
        ),
        migrations.AddField(
            model_name='treatments',
            name='BeforeImage',
            field=models.ImageField(blank=True, null=True, upload_to='treatments/'),
        ),
    ]
