# Generated by Django 6.0.7 on 2026-07-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_treatments_afterimage_treatments_beforeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
    ]
