# Generated by Django 6.0.7 on 2026-07-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patients_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Username', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=20)),
                ('Action', models.TextField()),
            ],
        ),
    ]
