# Generated by Django 6.0.7 on 2026-07-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='Dr. Pakhare', max_length=100)),
                ('bio', models.TextField(default='Leading dental care specialist providing advanced treatments.')),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('email', models.EmailField(default='info@drpakharedental.com', max_length=100)),
                ('address', models.TextField(default='123 Healthcare Avenue, Medical District')),
                ('working_hours', models.CharField(default='Mon - Sat: 9:00 AM - 8:30 PM', max_length=100)),
                ('experience_years', models.CharField(default='Since 1990', max_length=50)),
                ('instagram_link', models.URLField(blank=True, default='https://instagram.com', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_photo', models.ImageField(blank=True, null=True, upload_to='reviews/profiles/')),
                ('treatment_photo', models.ImageField(blank=True, null=True, upload_to='reviews/treatments/')),
                ('review_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website_images/')),
                ('category', models.CharField(choices=[('CLINIC', 'Clinic'), ('GALLERY', 'Gallery')], max_length=20)),
            ],
        ),
    ]
