# Generated by Django 6.0.7 on 2026-07-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clinicprofile_patientreview_websiteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteimage',
            name='category',
            field=models.CharField(choices=[('PROFILE', 'Doctor Profile Photos'), ('GALLERY', 'Sliding Gallery Photos')], max_length=20),
        ),
    ]
